### ISSUE TITLE
Sometimes crash on arch-linux

### ISSUE THREAD

**Issue by empirephoenix** [empirephoenix/JME3-JFX#9]
The program 'java' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 5392 error_code 143 request_code 141 minor_code 7)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by empirephoenix** [comment]
Seems to only happen in the tests, not in any larger application.
-> Suspect some jvm internal synchronisation problems with jfx frame creation?

**Comment by davidB** [comment]
I'm on archlinux, I don't remember having this issue, I'll take care.

**Comment by empirephoenix** [comment]
Fixed, by including default settings for javafx, that both increase the performance and prevent driver/rendering system incompability based problems.
